# all availiable players
players = [
    "Айрапетян", 
    "Бабуров",
    "Новиков", 
    "Бирюков", 
    "Тюпаков",
    "Комнатный",
    "Стрижов",
    "Почепец",
    "Колесников",
    "Чечин",
    "Жестеров",
    "Селиванов",
    "Костик",
    "Слинько",
    "Кузнецов",
    "Мурзинов",
    "Букин",
    "Сидоров",
    "Заика", 
    "Спиридонов",
    "Малых",
    "Степанов"
    ]


player_ratings = {
    "Айрапетян": 5,
    "Бабуров": 1,
    "Новиков": 4,
    "Бирюков": 3,
    "Тюпаков": 4,
    "Комнатный": 5,
    "Стрижов": 3,
    "Почепец": 4,
    "Колесников": 5,
    "Чечин": 2,
    "Жестеров": 1,
    "Селиванов": 3,
    "Костик": 1,
    "Слинько": 0,
    "Кузнецов": 0,
    "Мурзинов": 7,
    "Букин": 2,
    "Заика": 2,
    "Сидоров": 1,
    "Спиридонов": 0,
    "Малых": 1, 
    "Степанов": 1
}

telegram_usernames = {
    "atcartsid": "Sidorov",
    "strzhv_d": "Strizhov",
    "Romzes666": "Zaika",
    "aerovit": "Tiupakov",
    "desmatch": "Kostik",
    "r1_sh2": "Slinko",
    "naz_zhe": "Zhesterov",
    "???": "Spiridonov",
    "consciousness007": "Pochepets",
    "mmurz": "Murzinov",
    "????": "Kolesnikov",
    "niksercatc": "Chechin",
    "dmalykhh": "Malykh",
    "Romch_77": "Baburov",
    "one_xtra": "Stepanov",
    "Mikel_Dudikoff": "Bukin",
    "komnatnyiegor": "Komnatniy",
    "??": "Ayrapetian",
    "salivanatc": "Selivanov",
    "?": "Kuznetsov",
    "?????": "Biriukov",
    "Alexgreensleeves": "Novikov"
}
